# Generated by Django 5.1.15 on 2026-03-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('poziom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'przedmiot',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('tel_num', models.CharField(blank=True, max_length=20, null=True)),
                ('haslo', models.CharField(max_length=128)),
                ('typ', models.CharField(default='uczen', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True, null=True)),
                ('stawka_godzinowa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('przedmioty', models.ManyToManyField(db_table='tutor_przedmiot', related_name='tutorzy', to='main.przedmiot')),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='main.user')),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posty', to='main.tutor')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Dostepnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.IntegerField()),
                ('godzina_od', models.TimeField()),
                ('godzina_do', models.TimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostepnosci', to='main.tutor')),
            ],
            options={
                'db_table': 'dostepnosc',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='main.post')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze_uzytkownika', to='main.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
