# Generated by Codex on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="przedmiot",
            name="temat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
