# Generated by Django 4.2.29 on 2026-03-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_przedmiot_temat_tutor_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinia_od', to='main.user')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie_dla', to='main.tutor')),
            ],
        ),
    ]
