# Generated by Django 4.2.29 on 2026-03-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_przedmiot_temat_tutor_rating'),
    ]

    # The Opinie model was already introduced on the sibling branch in
    # 0002_opinie. Keeping this branch empty allows fresh databases to apply the
    # merge history without attempting to create the same table twice.
    operations = []
