# Generated by Django 4.2.29 on 2026-03-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_opinie'),
        ('main', '0003_opinie'),
    ]

    operations = [
    ]
