# Generated by Django 5.1.15 on 2026-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_opinia_delete_opinie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostepnosc',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='avatar_tone',
            field=models.CharField(blank=True, default='slate', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='experience_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='status_badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutor',
            name='wiek',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
