# Generated by Django 5.1.15 on 2026-04-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clear_custom_user_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='haslo',
        ),
    ]
