# Generated by Django 5.1.15 on 2026-04-15 00:00

import re

from django.db import migrations, models


def _normalize_email(value):
    return (value or "").strip().lower()


def _build_username_base(custom_user, auth_username=""):
    if auth_username:
        base_value = auth_username
    else:
        email = _normalize_email(getattr(custom_user, "email", ""))
        if email and "@" in email:
            base_value = email.split("@", 1)[0]
        else:
            base_value = f"user-{custom_user.pk}"

    normalized_value = re.sub(r"[^\\w.@+-]", "-", (base_value or "").strip())
    normalized_value = normalized_value.strip("-._")
    return normalized_value or f"user-{custom_user.pk}"


def _make_unique_username(base_value, used_values):
    trimmed_base = (base_value or "user")[:150]
    lowered_candidate = trimmed_base.lower()
    if lowered_candidate not in used_values:
        used_values.add(lowered_candidate)
        return trimmed_base

    suffix = 1
    while True:
        suffix_label = f"-{suffix}"
        candidate = f"{trimmed_base[:150 - len(suffix_label)]}{suffix_label}"
        lowered_candidate = candidate.lower()
        if lowered_candidate not in used_values:
            used_values.add(lowered_candidate)
            return candidate
        suffix += 1


def populate_usernames(apps, schema_editor):
    AuthUser = apps.get_model("auth", "User")
    CustomUser = apps.get_model("main", "User")

    auth_usernames_by_email = {
        _normalize_email(auth_user.email): auth_user.username
        for auth_user in AuthUser.objects.exclude(email="")
    }

    used_usernames = set()

    for custom_user in CustomUser.objects.order_by("id"):
        auth_username = auth_usernames_by_email.get(_normalize_email(custom_user.email), "")
        base_value = _build_username_base(custom_user, auth_username=auth_username)
        custom_user.username = _make_unique_username(base_value, used_usernames)
        custom_user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_user_haslo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(
            populate_usernames,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
