# Generated by Django 5.1.15 on 2026-04-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_0011_notification_0012_user_username_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na akceptację'), ('accepted', 'Zaakceptowane'), ('declined', 'Odrzucone'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.dostepnosc')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.user')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.tutor')),
            ],
            options={
                'db_table': 'booking',
                'constraints': [models.UniqueConstraint(fields=('student', 'availability'), name='unique_student_booking_per_slot')],
            },
        ),
    ]
